In [ ]:
%pip install -U peft bitsandbytes transformers accelerate

In [ ]:
%pip install PyMuPDF

In [ ]:
%pip install -U trl

### Custom Dataset

In [4]:
from google.colab import files
upload = files.upload()

Saving Metformin.pdf to Metformin.pdf

In [5]:
import fitz
def ExtractText(pdf_path):
  textData = []
  with fitz.open(pdf_path) as doc:
    for page in doc:
      text = page.get_text("text").strip()
      if text:
        textData.append(text)
  return textData

In [6]:
pdfPath = "/content/Metformin.pdf"
content = ExtractText(pdfPath)
content

['Metformin is one of the most widely prescribed oral antihyperglycemic agents.\u200b\n Its primary mechanism of action involves the activation of AMP-activated protein kinase \n(AMPK), a central metabolic regulator that promotes glucose uptake and fatty acid oxidation \nwhile inhibiting hepatic gluconeogenesis.\u200b\n Beyond its glycemic control, Metformin has been shown to improve cardiovascular outcomes \nand display anti-inflammatory properties.\u200b\n Recent studies also suggest potential anticancer effects through inhibition of the mTOR \nsignaling pathway and suppression of tumor angiogenesis. \n \nClinical trials have demonstrated that combining Atorvastatin with Ezetimibe results in \nsignificant reductions in low-density lipoprotein cholesterol (LDL-C) levels compared to \nmonotherapy.\u200b\n Ezetimibe acts by inhibiting the Niemann–Pick C1-like 1 (NPC1L1) transporter in the intestinal \nwall, reducing cholesterol absorption, while Atorvastatin inhibits hepatic HMG-CoA reductase, \nsuppressing endogenous cholesterol synthesis.\u200b\n The dual mechanism provides an additive lipid-lowering effect, particularly beneficial for \npatients with familial hypercholesterolemia who are unresponsive to statins alone. \n \nThe success of mRNA vaccines against SARS-CoV-2 has opened new pathways for rapid \nvaccine development.\u200b\n mRNA platforms enable flexible design and quick adaptation to emerging viral variants such as \nBQ.1 and XBB.1.5.\u200b\n Phase-II clinical trials have shown strong immunogenicity with elevated neutralizing antibody \ntiters and robust CD8⁺ T-cell responses.\u200b\n Ongoing research is exploring thermostable formulations and self-amplifying mRNA constructs \nto enhance global distribution and cost-efficiency. \n \nArtificial intelligence (AI) is transforming pharmaceutical research by accelerating target \nidentification, molecular docking, and compound screening.\u200b\n Deep learning models trained on large-scale biological datasets can predict protein–ligand \nbinding affinities and optimize lead compounds.\u200b\n Integrating AI-driven insights with laboratory automation is reducing discovery timelines from \nyears to months.\u200b\n However, challenges remain regarding interpretability, bias mitigation, and regulatory validation \nfor AI-generated molecules.']

In [7]:
# Splitting
import re
def ChunkDataset(pages):
  chunksData = []
  for page in pages:
    chunks = re.split(r'\n\s*\n', page)
    for chunk in chunks:
      cleanedText = chunk.strip()
      if len(cleanedText) > 30:
        chunksData.append(cleanedText)
  return chunksData

In [8]:
chunks = ChunkDataset(content)
print(len(chunks))
print(chunks[0])

4
Metformin is one of the most widely prescribed oral antihyperglycemic agents.​
 Its primary mechanism of action involves the activation of AMP-activated protein kinase
(AMPK), a central metabolic regulator that promotes glucose uptake and fatty acid oxidation
while inhibiting hepatic gluconeogenesis.​
 Beyond its glycemic control, Metformin has been shown to improve cardiovascular outcomes
and display anti-inflammatory properties.​
 Recent studies also suggest potential anticancer effects through inhibition of the mTOR
signaling pathway and suppression of tumor angiogenesis.

In [9]:
data = [{"text" : chunk} for chunk in chunks]
for d in data:
  print(d)
  print()

{'text': 'Metformin is one of the most widely prescribed oral antihyperglycemic agents.\u200b\n Its primary mechanism of action involves the activation of AMP-activated protein kinase \n(AMPK), a central metabolic regulator that promotes glucose uptake and fatty acid oxidation \nwhile inhibiting hepatic gluconeogenesis.\u200b\n Beyond its glycemic control, Metformin has been shown to improve cardiovascular outcomes \nand display anti-inflammatory properties.\u200b\n Recent studies also suggest potential anticancer effects through inhibition of the mTOR \nsignaling pathway and suppression of tumor angiogenesis.'}

{'text': 'Clinical trials have demonstrated that combining Atorvastatin with Ezetimibe results in \nsignificant reductions in low-density lipoprotein cholesterol (LDL-C) levels compared to \nmonotherapy.\u200b\n Ezetimibe acts by inhibiting the Niemann–Pick C1-like 1 (NPC1L1) transporter in the intestinal \nwall, reducing cholesterol absorption, while Atorvastatin inhibits hepatic HMG-CoA reductase, \nsuppressing endogenous cholesterol synthesis.\u200b\n The dual mechanism provides an additive lipid-lowering effect, particularly beneficial for \npatients with familial hypercholesterolemia who are unresponsive to statins alone.'}

{'text': 'The success of mRNA vaccines against SARS-CoV-2 has opened new pathways for rapid \nvaccine development.\u200b\n mRNA platforms enable flexible design and quick adaptation to emerging viral variants such as \nBQ.1 and XBB.1.5.\u200b\n Phase-II clinical trials have shown strong immunogenicity with elevated neutralizing antibody \ntiters and robust CD8⁺ T-cell responses.\u200b\n Ongoing research is exploring thermostable formulations and self-amplifying mRNA constructs \nto enhance global distribution and cost-efficiency.'}

{'text': 'Artificial intelligence (AI) is transforming pharmaceutical research by accelerating target \nidentification, molecular docking, and compound screening.\u200b\n Deep learning models trained on large-scale biological datasets can predict protein–ligand \nbinding affinities and optimize lead compounds.\u200b\n Integrating AI-driven insights with laboratory automation is reducing discovery timelines from \nyears to months.\u200b\n However, challenges remain regarding interpretability, bias mitigation, and regulatory validation \nfor AI-generated molecules.'}

In [10]:
# Model Selection
model_name = "Qwen/Qwen2.5-0.5B"

In [11]:
from transformers import AutoTokenizer, AutoModelForCausalLM, Trainer, TrainingArguments, DataCollatorForLanguageModeling

In [12]:
tokenizer = AutoTokenizer.from_pretrained(model_name) # load the correct tokenizer for the model
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/681 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [13]:
def TokenizeText(data):
  tokens = tokenizer(data["text"], padding="max_length", truncation=True, max_length=512)
  tokens["labels"] = tokens["input_ids"].copy()
  return tokens

In [16]:
from datasets import Dataset, load_dataset

In [17]:
customDataset = Dataset.from_list(data)
customDataset

Dataset({
    features: ['text'],
    num_rows: 4
})

In [18]:
tokenizedData = customDataset.map(TokenizeText, batched = True, remove_columns = ["text"])

Map:   0%|          | 0/4 [00:00<?, ? examples/s]

In [19]:
tokenizedData

Dataset({
    features: ['input_ids', 'attention_mask', 'labels'],
    num_rows: 4
})

In [20]:
model = AutoModelForCausalLM.from_pretrained(model_name)

model.safetensors:   0%|          | 0.00/988M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/290 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/138 [00:00<?, ?B/s]

In [21]:
from transformers import TrainingArguments
help(TrainingArguments)

Help on class TrainingArguments in module transformers.training_args:

class TrainingArguments(builtins.object)
 |  TrainingArguments(output_dir: str | None = None, per_device_train_batch_size: int = 8, num_train_epochs: float = 3.0, max_steps: int = -1, learning_rate: float = 5e-05, lr_scheduler_type: transformers.trainer_utils.SchedulerType | str = 'linear', lr_scheduler_kwargs: dict | str | None = None, warmup_steps: float = 0, optim: transformers.training_args.OptimizerNames | str = 'adamw_torch_fused', optim_args: str | None = None, weight_decay: float = 0.0, adam_beta1: float = 0.9, adam_beta2: float = 0.999, adam_epsilon: float = 1e-08, optim_target_modules: None | str | list[str] = None, gradient_accumulation_steps: int = 1, average_tokens_across_devices: bool = True, max_grad_norm: float = 1.0, label_smoothing_factor: float = 0.0, bf16: bool = False, fp16: bool = False, bf16_full_eval: bool = False, fp16_full_eval: bool = False, tf32: bool | None = None, gradient_checkpointing: bool = False, gradient_checkpointing_kwargs: dict[str, typing.Any] | str | None = None, torch_compile: bool = False, torch_compile_backend: str | None = None, torch_compile_mode: str | None = None, use_liger_kernel: bool = False, liger_kernel_config: dict[str, bool] | None = None, use_cache: bool = False, neftune_noise_alpha: float | None = None, torch_empty_cache_steps: int | None = None, auto_find_batch_size: bool = False, logging_strategy: transformers.trainer_utils.IntervalStrategy | str = 'steps', logging_steps: float = 500, logging_first_step: bool = False, log_on_each_node: bool = True, logging_nan_inf_filter: bool = True, include_num_input_tokens_seen: str | bool = 'no', log_level: str = 'passive', log_level_replica: str = 'warning', disable_tqdm: bool | None = None, report_to: None | str | list[str] = 'none', run_name: str | None = None, project: str = 'huggingface', trackio_space_id: str | None = 'trackio', eval_strategy: transformers.trainer_utils.IntervalStrategy | str = 'no', eval_steps: float | None = None, eval_delay: float = 0, per_device_eval_batch_size: int = 8, prediction_loss_only: bool = False, eval_on_start: bool = False, eval_do_concat_batches: bool = True, eval_use_gather_object: bool = False, eval_accumulation_steps: int | None = None, include_for_metrics: list[str] = <factory>, batch_eval_metrics: bool = False, save_only_model: bool = False, save_strategy: transformers.trainer_utils.SaveStrategy | str = 'steps', save_steps: float = 500, save_on_each_node: bool = False, save_total_limit: int | None = None, enable_jit_checkpoint: bool = False, push_to_hub: bool = False, hub_token: str | None = None, hub_private_repo: bool | None = None, hub_model_id: str | None = None, hub_strategy: transformers.trainer_utils.HubStrategy | str = 'every_save', hub_always_push: bool = False, hub_revision: str | None = None, load_best_model_at_end: bool = False, metric_for_best_model: str | None = None, greater_is_better: bool | None = None, ignore_data_skip: bool = False, restore_callback_states_from_checkpoint: bool = False, full_determinism: bool = False, seed: int = 42, data_seed: int | None = None, use_cpu: bool = False, accelerator_config: dict | str | None = None, parallelism_config: accelerate.parallelism_config.ParallelismConfig | None = None, dataloader_drop_last: bool = False, dataloader_num_workers: int = 0, dataloader_pin_memory: bool = True, dataloader_persistent_workers: bool = False, dataloader_prefetch_factor: int | None = None, remove_unused_columns: bool = True, label_names: list[str] | None = None, train_sampling_strategy: str = 'random', length_column_name: str = 'length', ddp_find_unused_parameters: bool | None = None, ddp_bucket_cap_mb: int | None = None, ddp_broadcast_buffers: bool | None = None, ddp_backend: str | None = None, ddp_timeout: int = 1800, fsdp: list[transformers.trainer_utils.FSDPOption] | str | None = None, fsdp_config: dict[str, typing.Any] | str | None = None, deepspeed: dict | str | None = None, debug: str | list[transformers.debug_utils.DebugOption] = '', skip_memory_metrics: bool = True, do_train: bool = False, do_eval: bool = False, do_predict: bool = False, resume_from_checkpoint: str | None = None, warmup_ratio: float | None = None, logging_dir: str | None = None, local_rank: int = -1) -> None
 |
 |  Configuration class for controlling all aspects of model training with the Trainer.
 |  TrainingArguments centralizes all hyperparameters, optimization settings, logging preferences, and infrastructure choices needed for training.
 |
 |  [`HfArgumentParser`] can turn this class into
 |  [argparse](https://docs.python.org/3/library/argparse#module-argparse) arguments that can be specified on the
 |  command line.
 |
 |  Parameters:
 |      output_dir (`str`, *optional*, defaults to `"trainer_output"`):
 |          The output directory where the model predictions and checkpoints will be written.
 |
 |      > Training Duration and Batch Size
 |
 |      per_device_train_batch_size (`int`, *optional*, defaults to 8):
 |          The batch size *per device*. The **global batch size** is computed as:
 |          `per_device_train_batch_size * number_of_devices` in multi-GPU or distributed setups.
 |      num_train_epochs(`float`, *optional*, defaults to 3.0):
 |          Total number of training epochs to perform (if not an integer, will perform the decimal part percents of
 |          the last epoch before stopping training).
 |      max_steps (`int`, *optional*, defaults to -1):
 |          Overrides `num_train_epochs`. If set to a positive number, the total number of training steps to perform.
 |          For a finite dataset, training is reiterated through the dataset (if all data is exhausted) until
 |          `max_steps` is reached.
 |
 |      > Learning Rate & Scheduler
 |
 |      learning_rate (`float`, *optional*, defaults to 5e-5):
 |          The initial learning rate for the optimizer. This is typically the peak learning rate when using a scheduler with warmup.
 |      lr_scheduler_type (`str` or [`SchedulerType`], *optional*, defaults to `"linear"`):
 |          The learning rate scheduler type to use. See [`SchedulerType`] for all possible values. Common choices:
 |              - "linear" = [`get_linear_schedule_with_warmup`]
 |              - "cosine" = [`get_cosine_schedule_with_warmup`]
 |              - "constant" =  [`get_constant_schedule`]
 |              - "constant_with_warmup" = [`get_constant_schedule_with_warmup`]
 |      lr_scheduler_kwargs (`dict` or `str`, *optional*, defaults to `None`):
 |          The extra arguments for the lr_scheduler. See the documentation of each scheduler for possible values.
 |      warmup_steps (`int` or `float`, *optional*, defaults to 0):
 |          Number of steps for a linear warmup from 0 to `learning_rate`. Warmup helps stabilize training in the initial phase. Can be:
 |              - An integer: exact number of warmup steps
 |              - A float in range [0, 1): interpreted as ratio of total training steps
 |
 |      > Optimizer
 |
 |      optim (`str` or [`training_args.OptimizerNames`], *optional*, defaults to `"adamw_torch"` (for torch>=2.8 `"adamw_torch_fused"`)):
 |          The optimizer to use. Common options:
 |              - `"adamw_torch"`: PyTorch's AdamW (recommended default)
 |              - `"adamw_torch_fused"`: Fused AdamW kernel
 |              - `"adamw_hf"`: HuggingFace's AdamW implementation
 |              - `"sgd"`: Stochastic Gradient Descent with momentum
 |              - `"adafactor"`: Memory-efficient optimizer for large models
 |              - `"adamw_8bit"`: 8-bit AdamW (requires bitsandbytes)
 |              See [`OptimizerNames`] for the complete list.
 |      optim_args (`str`, *optional*):
 |          Optional arguments that are supplied to optimizers such as AnyPrecisionAdamW, AdEMAMix, and GaLore.
 |      weight_decay (`float`, *optional*, defaults to 0):
 |          Weight decay coefficient applied by the optimizer (not the loss function). Adds L2
 |          regularization to prevent overfitting by penalizing large weights. Automatically
 |          excluded from bias and LayerNorm parameters. Typical values: 0.01 (standard), 0.1
 |          (stronger regularization), 0.0 (no regularization).
 |      adam_beta1 (`float`, *optional*, defaults to 0.9):
 |          The exponential decay rate for the first moment estimates (momentum) in Adam-based
 |          optimizers. Controls how much history of gradients to retain.
 |      adam_beta2 (`float`, *optional*, defaults to 0.999):
 |          The exponential decay rate for the second moment estimates (variance) in Adam-based
 |          optimizers. Controls adaptive learning rate scaling.
 |      adam_epsilon (`float`, *optional*, defaults to 1e-8):
 |          Epsilon value for numerical stability in Adam-based optimizers. Prevents division by
 |          zero in the denominator of the update rule.
 |      optim_target_modules (`Union[str, list[str]]`, *optional*):
 |          The target modules to optimize, i.e. the module names that you would like to train.
 |          Currently used for the [GaLore algorithm](https://huggingface.co/papers/2403.03507) and [APOLLO algorithm](https://huggingface.co/papers/2412.05270).
 |          See [GaLore implementation](https://github.com/jiaweizzhao/GaLore) and [APOLLO implementation](https://github.com/zhuhanqing/APOLLO) for more details.
 |          You need to make sure to pass a valid GaLore or APOLLO optimizer, e.g., one of: "apollo_adamw", "galore_adamw", "galore_adamw_8bit", "galore_adafactor" and make sure that the target modules are `nn.Linear` modules only.
 |
 |      > Regularization & Training Stability
 |
 |      gradient_accumulation_steps (`int`, *optional*, defaults to 1):
 |          Number of update steps to accumulate gradients before performing a backward/update pass.
 |          Simulates larger batch sizes without additional memory. Effective batch size =
 |          `per_device_train_batch_size × num_devices × gradient_accumulation_steps`.
 |          > [!TIP]
 |          > When using gradient accumulation, one "step" is counted as one step with a backward pass. Therefore, logging, evaluation, and saving will occur every `gradient_accumulation_steps × xxx_step` training examples.
 |      average_tokens_across_devices (`bool`, *optional*, defaults to `True`):
 |          Whether or not to average tokens across devices. If enabled, will use all_reduce to synchronize
 |          num_tokens_in_batch for precise loss calculation. Reference:
 |          https://github.com/huggingface/transformers/issues/34242
 |      max_grad_norm (`float`, *optional*, defaults to 1.0):
 |          Maximum gradient norm for gradient clipping. Applied after backward pass, before
 |          optimizer step. Prevents gradient explosion by scaling down gradients when their global
 |          norm exceeds this threshold. Set to 0 to disable clipping. Typical values:
 |          1.0 (standard), 0.5 (more conservative), 5.0 (less aggressive).
 |      label_smoothing_factor (`float`, *optional*, defaults to 0.0):
 |          Label smoothing factor to prevent overconfidence. Replaces hard 0/1 targets with soft
 |          targets: 0 becomes `ε/num_labels` and 1 becomes `1 - ε + ε/num_labels`, where
 |          ε = `label_smoothing_factor`. Zero means no smoothing. Typical range: 0.0 to 0.1.
 |
 |      > Mixed Precision Training
 |
 |      bf16 (`bool`, *optional*, defaults to `False`):
 |          Enable bfloat16 (BF16) mixed precision training
 |          Generally preferred over FP16 due to better numerical stability and no loss scaling required.
 |      fp16 (`bool`, *optional*, defaults to `False`):
 |          Enable float16 (FP16) mixed precision training.
 |          Consider using BF16 instead if your hardware supports it.
 |      bf16_full_eval (`bool`, *optional*, defaults to `False`):
 |          Use full BF16 precision for evaluation (not just mixed precision). Faster and saves
 |          memory but may affect metric values slightly. Only applies during evaluation.
 |      fp16_full_eval (`bool`, *optional*, defaults to `False`):
 |          Use full FP16 precision for evaluation (not just mixed precision). Faster and saves
 |          memory but may affect metric values slightly. Only applies during evaluation.
 |      tf32 (`bool`, *optional*):
 |          Enable TensorFloat-32 (TF32) mode on Ampere and newer GPUs. TF32 uses 19-bit precision
 |          for matrix multiplications (instead of FP32's 23-bit), providing up to 8x speedup with
 |          negligible accuracy loss. Default depends on PyTorch version. See
 |          [TF32 docs](https://huggingface.co/docs/transformers/perf_train_gpu_one#tf32).
 |
 |      > Gradient Checkpointing
 |
 |      gradient_checkpointing (`bool`, *optional*, defaults to `False`):
 |          Enable gradient checkpointing to trade compute for memory. Reduces memory usage by
 |          clearing activations during forward pass and recomputing them during backward pass.
 |          Enables training larger models or batch sizes at the cost of ~20% slower training.
 |      gradient_checkpointing_kwargs (`dict`, *optional*, defaults to `None`):
 |          Keyword arguments passed to `gradient_checkpointing_enable()`.
 |
 |      > Compilation
 |
 |      torch_compile (`bool`, *optional*, defaults to `False`):
 |          Compile the model using PyTorch 2.0's `torch.compile()` for faster training. Can provide
 |          20-50% speedup with no code changes. Uses default compilation settings unless
 |          `torch_compile_backend` or `torch_compile_mode` are specified.
 |      torch_compile_backend (`str`, *optional*):
 |          Backend for `torch.compile()`. If set, automatically enables `torch_compile`. Options
 |          include `"inductor"` (default), `"aot_eager"`, `"cudagraphs"`. Backends vary by PyTorch
 |          version - see PyTorch docs for available options.
 |      torch_compile_mode (`str`, *optional*):
 |          Compilation mode for `torch.compile()`. If set, automatically enables `torch_compile`.
 |          Options: `"default"`, `"reduce-overhead"` (minimize Python overhead), `"max-autotune"`
 |          (aggressive optimization, slower compile time).
 |
 |      > Kernels
 |
 |      use_liger_kernel (`bool`, *optional*, defaults to `False`):
 |          Enable [Liger Kernel](https://github.com/linkedin/Liger-Kernel) optimizations. Increases
 |          multi-GPU throughput by ~20% and reduces memory usage by ~60%. Works with Flash Attention,
 |          FSDP, and DeepSpeed. Currently supports Llama, Mistral, Mixtral, and Gemma models.
 |      liger_kernel_config (`Optional[dict]`, *optional*):
 |          Configuration for Liger Kernel. Passed as kwargs to `_apply_liger_kernel_to_instance()`.
 |          Options typically include: `"rope"`, `"swiglu"`, `"cross_entropy"`,
 |          `"fused_linear_cross_entropy"`, `"rms_norm"`. If `None`, uses default configuration.
 |
 |      > Additional Optimizations
 |
 |      use_cache (`bool`, *optional*, defaults to `False`):
 |          Whether or not to enable cache for the model. For training, this is usually not needed apart from some PEFT methods that uses `past_key_values`.
 |      neftune_noise_alpha (`Optional[float]`):
 |          If not `None`, this will activate NEFTune noise embeddings. This can drastically improve model performance
 |          for instruction fine-tuning. Check out the [original paper](https://huggingface.co/papers/2310.05914) and the
 |          [original code](https://github.com/neelsjain/NEFTune). Support transformers `PreTrainedModel` and also
 |          `PeftModel` from peft. The original paper used values in the range [5.0, 15.0].
 |      torch_empty_cache_steps (`int`, *optional*):
 |          Number of steps to wait before calling `torch.<device>.empty_cache()`. If left unset or set to None, cache will not be emptied.
 |          This can help avoid CUDA out-of-memory errors by lowering peak VRAM usage at a cost of about [10% slower performance](https://github.com/huggingface/transformers/issues/31372).
 |      auto_find_batch_size (`bool`, *optional*, defaults to `False`)
 |          Whether to find a batch size that will fit into memory automatically through exponential decay, avoiding
 |          CUDA Out-of-Memory errors.
 |
 |      > Logging & Monitoring Training
 |
 |      logging_strategy (`str` or [`~trainer_utils.IntervalStrategy`], *optional*, defaults to `"steps"`):
 |          The logging strategy to adopt during training. Possible values are:
 |              - `"no"`: No logging is done during training.
 |              - `"epoch"`: Logging is done at the end of each epoch.
 |              - `"steps"`: Logging is done every `logging_steps`.
 |      logging_steps (`int` or `float`, *optional*, defaults to 500):
 |          Number of update steps between two logs if `logging_strategy="steps"`. Should be an integer or a float in
 |          range `[0,1)`. If smaller than 1, will be interpreted as ratio of total training steps.
 |      logging_first_step (`bool`, *optional*, defaults to `False`):
 |          Whether to log the first `global_step` or not.
 |      log_on_each_node (`bool`, *optional*, defaults to `True`):
 |          In multinode distributed training, whether to log using `log_level` once per node, or only on the main
 |          node.
 |      logging_nan_inf_filter (`bool`, *optional*, defaults to `True`):
 |           Filter out NaN and Inf losses when logging. If `True`, replaces NaN/Inf losses with the
 |          average of recent valid losses. Does not affect gradient computation, only logging.
 |      include_num_input_tokens_seen (`Optional[Union[str, bool]]`, *optional*, defaults to "no"):
 |          Whether to track the number of input tokens seen. Must be one of ["all", "non_padding", "no"] or a boolean value which map to "all" or "no".
 |          May be slower in distributed training as gather operations must be called.
 |
 |      > Logging
 |
 |      log_level (`str`, *optional*, defaults to `passive`):
 |          Logging level for the main process. Options: `"debug"`, `"info"`, `"warning"`, `"error"`,
 |          `"critical"`, or `"passive"` (doesn't change the current Transformers logging level,
 |          which defaults to `"warning"`)
 |      log_level_replica (`str`, *optional*, defaults to `"warning"`):
 |          Logging level for replica processes in distributed training. Same options as `log_level`.
 |      disable_tqdm (`bool`, *optional*):
 |          Disable tqdm progress bars. Defaults to `True` if `log_level` is warning or lower, `False` otherwise.
 |
 |      > Experiment Tracking Integration
 |
 |      report_to (`str` or `list[str]`, *optional*, defaults to `"none"`):
 |          The list of integrations to report the results and logs to. Supported platforms are `"azure_ml"`,
 |          `"clearml"`, `"codecarbon"`, `"comet_ml"`, `"dagshub"`, `"dvclive"`, `"flyte"`, `"mlflow"`, `"swanlab"`,
 |          `"tensorboard"`, `"trackio"` and `"wandb"`. Use `"all"` to report to all integrations installed, `"none"`
 |          for no integrations.
 |      run_name (`str`, *optional*):
 |          A descriptor for the run. Typically used for [trackio](https://github.com/gradio-app/trackio),
 |          [wandb](https://www.wandb.com/), [mlflow](https://www.mlflow.org/), [comet](https://www.comet.com/site) and
 |          [swanlab](https://swanlab.cn) logging.
 |      project (`str`, *optional*, defaults to `"huggingface"`):
 |          The name of the project to use for logging. Currently, only used by Trackio.
 |      trackio_space_id (`str` or `None`, *optional*, defaults to `"trackio"`):
 |          The Hugging Face Space ID to deploy to when using Trackio. Should be a complete Space name like
 |          `'username/reponame'` or `'orgname/reponame'`, or just `'reponame'` in which case the Space will be

In [22]:
trainingArgs = TrainingArguments(
    output_dir = "./Qwen-pharma-domain",
    num_train_epochs = 1,
    per_device_train_batch_size=2,
    save_steps=500,
    save_total_limit=2,
    logging_steps=50,
    learning_rate=2e-5,
    fp16=True,
    report_to="none"
)

### Partial Finetuning Method
* Method 1: Feerze some layer and finetune unfreeze layer(old CNN and Bert sytel method)

* Method 2: LORA(Append some external weight to the already trained pretrain weight)

In [ ]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, Trainer, TrainingArguments, DataCollatorForLanguageModeling
from datasets import load_dataset
import os, re

model_name = "Qwen/Qwen2.5-0.5B"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name, device_map="auto")

# Freeze all layers
for param in model.parameters():
     param.requires_grad = False

# Unfreeze last 4 transformer blocks + lm_head
for name, param in model.named_parameters():
    if any(f"model.layers.{i}." in name for i in range(20, 24)):
        param.requires_grad = True
    elif "lm_head" in name:
        param.requires_grad = True
    else:
        param.requires_grad = False

trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
total = sum(p.numel() for p in model.parameters())
print(f"Trainable: {trainable/total*100:.2f}% of total parameters")


dataset = load_dataset("json", data_files={"train": "pharma_non_instruction.jsonl"})

def TokenizeText(data):
  tokens = tokenizer(data["text"], padding="max_length", truncation=True, max_length=512)
  tokens["labels"] = tokens["input_ids"].copy()
  return tokens

tokenized = customDataset["train"].map(TokenizeText, batched=True, remove_columns=["text"])
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

os.environ["WANDB_DISABLED"] = "true"
training_args = TrainingArguments(
     output_dir="./tinyllama-pharma-last4",
     overwrite_output_dir=True,
     num_train_epochs=2,
     per_device_train_batch_size=2,
     gradient_accumulation_steps=4,
     learning_rate=1e-4,
     fp16=True,
     logging_steps=20,
     save_steps=200,
     save_total_limit=2,
     report_to="none"
)


trainer = Trainer(
     model=model,
     args=training_args,
     train_dataset=tokenized,
     data_collator=data_collator
)

trainer.train()
trainer.save_model("./Qwen-pharma-last4-final")
print("\nTraining completed and model saved!")

* Method 2

In [23]:
import torch, gc
gc.collect()
torch.cuda.empty_cache()

In [ ]:
!pip install transformers accelerate bitsandbytes peft datasets

In [25]:
from transformers import AutoTokenizer, AutoModelForCausalLM, TrainingArguments, Trainer
from peft import LoraConfig, get_peft_model, TaskType
from datasets import load_dataset

In [26]:
model_name = "Qwen/Qwen2.5-0.5B"
tokenizer = AutoTokenizer.from_pretrained(model_name)

In [27]:
def TokenizeText(data):
  tokens = tokenizer(data["text"], padding="max_length", truncation=True, max_length=512)
  tokens["labels"] = tokens["input_ids"].copy()
  return tokens

tokenized = customDataset.map(TokenizeText, batched=True, remove_columns=["text"])

Map:   0%|          | 0/4 [00:00<?, ? examples/s]

In [28]:
from transformers import BitsAndBytesConfig
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16
)

In [29]:
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map="auto"
)

Loading weights:   0%|          | 0/290 [00:00<?, ?it/s]

In [30]:
lora_config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    r=8,
    lora_alpha=16,
    target_modules=["q_proj","v_proj"],
    lora_dropout=0.05,
    bias="none"
)
non_inst_model_lora = get_peft_model(model, lora_config)

In [31]:
args = TrainingArguments(
    output_dir="./Qwen-lora",
    num_train_epochs=10,
    per_device_train_batch_size=1,
    gradient_accumulation_steps=8,
    learning_rate=2e-4,
    fp16=True,
    logging_steps=20,
    save_total_limit=1,
    report_to="none"
)

In [32]:
trainer = Trainer(
    model=non_inst_model_lora,
    args=args,
    train_dataset=tokenized
)

trainer.train()

TrainOutput(global_step=10, training_loss=11.907249450683594, metrics={'train_runtime': 44.8689, 'train_samples_per_second': 0.891, 'train_steps_per_second': 0.223, 'total_flos': 44044957777920.0, 'train_loss': 11.907249450683594, 'epoch': 10.0})

In [33]:
import os
print(os.listdir("/content"))
print(os.listdir("/content/Qwen-lora"))

['.config', 'Metformin.pdf', 'Qwen-lora', 'sample_data']
['checkpoint-10']

In [34]:
trainedModelPath = "/content/Qwen-lora"
from peft import PeftModel
from transformers import AutoModelForCausalLM

base_model = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map="auto"
)

trainedModel = PeftModel.from_pretrained(
    base_model,
    "/content/Qwen-lora/checkpoint-10"
)

Loading weights:   0%|          | 0/290 [00:00<?, ?it/s]

In [35]:
trainedModel.print_trainable_parameters()

trainable params: 0 || all params: 494,573,440 || trainable%: 0.0000

In [36]:
prompt = "Clinical trials demonstrated that combining Atorvastatin with Ezetimibe"
inputs = tokenizer(prompt, return_tensors="pt").to("cuda")
outputs = model.generate(
    **inputs,
    max_new_tokens=100,
    temperature=0.8,
    top_p=0.9,
    do_sample=True,
    repetition_penalty=1.1
)

print("\nModel Output:\n")
print(tokenizer.decode(outputs[0], skip_special_tokens=True))

Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.

Model Output:

Clinical trials demonstrated that combining Atorvastatin with Ezetimibe in patients with a history of acute myocardial infarction was associated with an increased risk of myocardial infarction or death, compared to patients who received ezetimibe alone. Thus far, the mechanism by which aztreonamine increases the efficacy of ezatoprost is not known.
The clinical trial results presented here suggest that aztreonamine may reduce plasma levels of prostanoids and their metabolites. In contrast, both ezetimide (a beta-

In [39]:
import shutil

folder_path = "/content/Qwen-lora"
output_zip = "/content/Qwen-lora"

shutil.make_archive(output_zip, 'zip', folder_path)

print("Zipping completed!")

Zipping completed!

In [40]:
import zipfile

zip_path = "/content/Qwen-lora.zip"
extract_path = "/content/"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Unzipping completed!")

Unzipping completed!

In [41]:
model_path = "/content/checkpoint-10"

nonInstructionModel = AutoModelForCausalLM.from_pretrained(model_path, device_map = "auto")

Loading weights:   0%|          | 0/290 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/96 [00:00<?, ?it/s]

In [42]:
prompt = "Clinical trials demonstrated that combining Atorvastatin with Ezetimibe"
inputs = tokenizer(prompt, return_tensors="pt").to("cuda")
outputs = nonInstructionModel.generate(
    **inputs,
    max_new_tokens=100,
    temperature=0.8,
    top_p=0.9,
    do_sample=True,
    repetition_penalty=1.1
)


print("\nModel Output:\n")
print(tokenizer.decode(outputs[0], skip_special_tokens=True))

Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.

Model Output:

Clinical trials demonstrated that combining Atorvastatin with Ezetimibe is effective in reducing LDL-C and increasing HDL-C levels. The study was conducted by the Department of Medicine, HSE University, in collaboration with a number of clinical research organizations.
The trial showed that the combination of Atorvastatin and Ezetimibe could effectively reduce LDL-C (low-density lipoprotein) in 10% to 20% of patients with high cholesterol levels who were not on statin medications. However, if they were already taking statins,

# Instructional Finetuning

* 1) Instructional Fintuning with Inbuilt Data

In [43]:
from datasets import load_dataset
dataset = load_dataset("Amod/mental_health_counseling_conversations", split="train")

README.md: 0.00B [00:00, ?B/s]

combined_dataset.json: 0.00B [00:00, ?B/s]

Generating train split:   0%|          | 0/3512 [00:00<?, ? examples/s]

In [44]:
dataset

Dataset({
    features: ['Context', 'Response'],
    num_rows: 3512
})

In [45]:
def format(example):
  question = example["Context"]
  answer = example["Response"]

  example["Text"] = f"[INST] {question} [/INST] {answer}"
  return example

In [46]:
formattedDataset = dataset.map(format)

Map:   0%|          | 0/3512 [00:00<?, ? examples/s]

In [49]:
formattedDataset[0]["Text"]

"[INST] I'm going through some things with my feelings and myself. I barely sleep and I do nothing but think about how I'm worthless and how I shouldn't be here.\n   I've never tried or contemplated suicide. I've always wanted to fix my issues, but I never get around to it.\n   How can I change my feeling of being worthless to everyone? [/INST] If everyone thinks you're worthless, then maybe you need to find new people to hang out with.Seriously, the social context in which a person lives is a big influence in self-esteem.Otherwise, you can go round and round trying to understand why you're not worthless, then go back to the same crowd and be knocked down again.There are many inspirational messages you can find in social media. \xa0Maybe read some of the ones which state that no person is worthless, and that everyone has a good purpose to their life.Also, since our culture is so saturated with the belief that if someone doesn't feel good about themselves that this is somehow terrible.Bad feelings are part of living. \xa0They are the motivation to remove ourselves from situations and relationships which do us more harm than good.Bad feelings do feel terrible. \xa0 Your feeling of worthlessness may be good in the sense of motivating you to find out that you are much better than your feelings today."

In [51]:
import pandas as pd
df = pd.DataFrame(dataset)
df

,Context,Response
0,I'm going through some things with my feelings...,"If everyone thinks you're worthless, then mayb..."
1,I'm going through some things with my feelings...,"Hello, and thank you for your question and see..."
2,I'm going through some things with my feelings...,First thing I'd suggest is getting the sleep y...
3,I'm going through some things with my feelings...,Therapy is essential for those that are feelin...
4,I'm going through some things with my feelings...,I first want to let you know that you are not ...
...,...,...
3507,My grandson's step-mother sends him to school ...,Absolutely not! It is never in a child's best ...
3508,My boyfriend is in recovery from drug addictio...,I'm sorry you have tension between you and you...
3509,The birth mother attempted suicide several tim...,"The true answer is, ""no one can really say wit..."
3510,I think adult life is making him depressed and...,How do you help yourself to believe you requir...
3511,I just took a job that requires me to travel f...,hmm this is a tough one!

In [52]:
df.to_csv("mental_health_counseling_conversations.csv", index=False)
df.to_json("mental_health_counseling_conversations.jsonl", orient="records", lines=True)

* 2) Custom Dataset

In [53]:
from google.colab import files
uploaded = files.upload()

Saving pharma_instruction_data.csv to pharma_instruction_data.csv

In [54]:
from datasets import load_dataset
dataset = load_dataset("csv", data_files = "/content/pharma_instruction_data.csv", split = "train")
dataset

Generating train split: 0 examples [00:00, ? examples/s]

Dataset({
    features: ['instruction', 'input', 'output'],
    num_rows: 5
})

In [57]:
def formatCustom(example):
  prompt = f"### Instruction:\n{example['instruction']}\n### Input:\n{example['input']}\n### Response:\n{example['output']}"
  return {"text": prompt}

dataset = dataset.map(formatCustom)
dataset[0]['text']

Map:   0%|          | 0/5 [00:00<?, ? examples/s]

'### Instruction:\nExplain the mechanism of action of Metformin.\n### Input:\nNone\n### Response:\nMetformin activates AMP-activated protein kinase (AMPK), which increases glucose uptake and fatty-acid oxidation while inhibiting hepatic gluconeogenesis, thereby lowering blood glucose.'

In [58]:
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

In [60]:
def tokenize(example):
    tokens = tokenizer(example["text"], truncation=True, padding="max_length", max_length=512)
    tokens["labels"] = tokens["input_ids"].copy()
    return tokens

In [61]:
tokenized = dataset.map(tokenize, batched=True)

Map:   0%|          | 0/5 [00:00<?, ? examples/s]

In [66]:
tokenized

Dataset({
    features: ['instruction', 'input', 'output', 'text', 'input_ids', 'attention_mask', 'labels'],
    num_rows: 5
})

In [67]:
from peft import LoraConfig, get_peft_model, TaskType

In [72]:
lora_config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    r=8,
    lora_alpha=16,
    target_modules=["q_proj","v_proj"],
    lora_dropout=0.05,
    bias="none"
)
model = get_peft_model(nonInstructionModel, lora_config) # lora model

/usr/local/lib/python3.12/dist-packages/peft/mapping_func.py:72: UserWarning: You are trying to modify a model with PEFT for a second time. If you want to reload the model with a different config, make sure to call `.unload()` before.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/peft/tuners/tuners_utils.py:285: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(

In [80]:
args = TrainingArguments(
    output_dir="./Qwen-instruction",
    num_train_epochs=12,
    per_device_train_batch_size=1,
    gradient_accumulation_steps=8,
    learning_rate=2e-4,
    fp16=True,
    logging_steps=20,
    save_total_limit=1,
    report_to="none"
)

In [81]:
trainer = Trainer(
    model=model,
    args=args,
    train_dataset=tokenized,
)

trainer.train()

TrainOutput(global_step=12, training_loss=0.6079001824061075, metrics={'train_runtime': 19.5224, 'train_samples_per_second': 3.073, 'train_steps_per_second': 0.615, 'total_flos': 66067436666880.0, 'train_loss': 0.6079001824061075, 'epoch': 12.0})

In [83]:
instruction_model_path = "/content/Qwen-instruction/checkpoint-12"
instructionalModel = AutoModelForCausalLM.from_pretrained(
    instruction_model_path,
    device_map="auto"
)

Loading weights:   0%|          | 0/290 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/96 [00:00<?, ?it/s]

In [84]:
prompt =  "Explain the mechanism of action of Metformin."
inputs = tokenizer(prompt, return_tensors="pt").to("cuda")

outputs = instructionalModel.generate(
    **inputs,
    max_new_tokens=100,
    temperature=0.8,
    top_p=0.9,
    do_sample=True,
    repetition_penalty=1.1
)

Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.

In [85]:
print("\nModel Output:\n")
print(tokenizer.decode(outputs[0], skip_special_tokens=True))

Model Output:

Explain the mechanism of action of Metformin. Metformin is an oral medication used to treat type 2 diabetes and other diseases with insulin resistance, such as non-insulin-dependent diabetes mellitus (NIDDM). The mechanism of action of metformin is through its inhibition of glucose transporters in liver, muscle, and fat cells.

Here's a simplified explanation:

1. Glucose uptake: Metformin blocks the binding of glucose to glucose transporter 1 (GLUT1) on hepatocytes, which are responsible for glucose uptake

In [86]:
questions = [
    "Explain the mechanism of action of Metformin.",
    "List two advantages of combining Atorvastatin with Ezetimibe.",
    "Summarize how mRNA vaccines work and mention one current research focus."
]

In [89]:
for q in questions:
    print("Question:", q)
    print("\n--- Non-instruction model ---")
    inputs = tokenizer(q, return_tensors="pt").to("cuda")
    outputs = nonInstructionModel.generate(**inputs, max_new_tokens=80)
    print(tokenizer.decode(outputs[0], skip_special_tokens=True))

    print("\n--- Instruction-tuned model ---")
    prompt = f"### Instruction:\n{q}\n### Input:\n\n### Response:\n"
    inputs = tokenizer(prompt, return_tensors="pt").to("cuda")
    outputs = instructionalModel.generate(**inputs, max_new_tokens=100)
    print(tokenizer.decode(outputs[0], skip_special_tokens=True))
    print("="*80, "\n")

Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.

Question: Explain the mechanism of action of Metformin.

--- Non-instruction model ---

Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.

Explain the mechanism of action of Metformin. Metformin is an oral antidiabetic drug that works by inhibiting the enzyme glucose-6-phosphate dehydrogenase (G6PD). This enzyme is responsible for the conversion of glucose to glucose-6-phosphate, which is a key step in the metabolism of glucose. When Metformin binds to the enzyme, it prevents the enzyme from functioning, thereby reducing the amount of glucose

--- Instruction-tuned model ---

Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.

### Instruction:
Explain the mechanism of action of Metformin.
### Input:

### Response:
Metformin is a dihydroxyacetone compound that is used to treat type 2 diabetes. It works by inhibiting the enzyme glucose-6-phosphatase, which is responsible for the breakdown of glucose in the liver. This leads to an increase in the production of glucose in the muscles and fat cells, which helps to lower blood glucose levels.
================================================================================

Question: List two advantages of combining Atorvastatin with Ezetimibe.

--- Non-instruction model ---

Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.

List two advantages of combining Atorvastatin with Ezetimibe. 1. Reduced risk of cardiovascular events: Atorvastatin and Ezetimibe work together to lower LDL cholesterol (bad cholesterol) and increase HDL cholesterol (good cholesterol). This combination can help reduce the risk of heart disease, stroke, and other cardiovascular events.

2. Improved lipid profile: Atorvastatin and Ezetimibe work together to lower LDL cholesterol and increase

--- Instruction-tuned model ---

Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.

### Instruction:
List two advantages of combining Atorvastatin with Ezetimibe.
### Input:

### Response:
1. Atorvastatin is a statin that is commonly used to treat high cholesterol and is known to reduce the risk of cardiovascular disease.
2. Ezetimibe is a drug that is commonly used to treat high cholesterol and is known to reduce the risk of cardiovascular disease.
================================================================================

Question: Summarize how mRNA vaccines work and mention one current research focus.

--- Non-instruction model ---

Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.

Summarize how mRNA vaccines work and mention one current research focus. mRNA vaccines work by encoding a specific protein or gene in a viral particle, which triggers the immune system to produce antibodies that can recognize and neutralize the virus. One current research focus is to develop mRNA vaccines for COVID-19, which have shown promising results in preclinical studies and have been approved for use in some countries.

--- Instruction-tuned model ---
### Instruction:
Summarize how mRNA vaccines work and mention one current research focus.
### Input:

### Response:
MRNA vaccines are a type of vaccine that uses messenger RNA (mRNA) to instruct cells to produce proteins that recognize and neutralize a pathogen. This process is called antigen presentation. The mRNA vaccine is delivered to the body through a vaccine platform, which is a combination of a vaccine and a carrier molecule. The mRNA is then translated into a protein that is recognized by the immune system. This protein is then recognized by the immune system and triggers an immune response.
================================================================================